nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-2.4.0.cjs

npmScopes:
  remix-run:
    npmRegistryServer: https://npm.remix.run
    npmAlwaysAuth: true
    npmAuthToken: ${REMIX_REGISTRY_TOKEN}
